### ISSUE TITLE
hover changes from build 542 and 543 need to be reverted (solved)

### ISSUE THREAD

**Issue by MarkSynth** [JeffMcClintock/SynthEdit-Bug-Tracking#24]
**UPDATE: i have fixed the problem by writing a new hover module. issue can be closed.**

@JeffMcClintock In builds 542 and 543, there has been an unintended change in the mouse hover behavior related to the hover overlay module i used for adjusting knobs. Previously, when interacting with knobs through the hover overlay, it was possible to click and drag to adjust a knob’s value while moving the mouse outside the visual boundary of the knob, maintaining control over the adjustment.

In these recent builds, however, dragging outside the hover overlay visual area immediately stops the adjustment.

Expected Behavior: When clicking on a knob to adjust its value:

The user should be able to drag the mouse outside the hover overlay visual frame (boundry box) without losing control over the value adjustment.
The dragging action should continue to influence the knob's (hover overlay) value as long as the mouse button remains pressed.

Current Behavior in Builds 542 and 543 and UP:

Dragging the mouse outside the knob’s (hover overlay) boundary causes the value adjustment to stop, requiring the user to stay within the small area of the knob, which reduces precision and ease of use.

Tag: Bug, SDK

**Comment by maxbreges** [comment]
>  it was possible to drag the mouse outside the visual 


It _**IS**_ possible. So not confirmed.
![hover](https://github.com/user-attachments/assets/d405a581-5343-4244-81b3-3814b2cafa82)

**Comment by DavidsonAudioMulti** [comment]
Which module? Can now no longer hold down a mouse button and adjust the value while dragging outside the visual bounding box.

I have hover in a couple modules and **can** move the knob outside the rect or knob box seem **fine** here in latest version?

**Comment by DavidsonAudioMulti** [comment]
![12345677](https://github.com/user-attachments/assets/04afb0f9-0c9f-483f-a4e3-708c71bfecc1)
Is working ok here seems fine??

**Comment by DavidsonAudioMulti** [comment]
I see I think that is a single sem Mouse not part of the free pack or some other pack could need an update because the older method was a little different. I think release is being called when not hover probably easy fix.

**Comment by maxbreges** [comment]
> the resize adorners

What is this?
Are you suggesting to revert changes because of a third-party module?
Shoudn't the third-party module be re-written?

**Comment by Sasha-Radojevic** [comment]
It is the problem with my module, which was made before SE had hover method in its SDK. My module needs to be re-written.

**Comment by DavidsonAudioMulti** [comment]
I figured it would be an easy fix. Mark does not see the sdk change part so I can see from his perspective that something broke, it is just that the hover is a little changed/improved now.  It is something to consider,  slight changes can throw off old work around or functions from 1.4.

Keeping 1.4 and 1.5 compatible could be a challenge as 1.4 gets further away from 1.5 or 1.6. It would be good to know what to expect with 1.6 and it seems 1.5 is still taking on minor features and many fixes.

**Comment by DavidsonAudioMulti** [comment]
Maybe possible breaking SDK changes could be denoted in the change log , things that could effect third party modules like SDK CHANGE or asterisk. It is kinda rare this happens I expected a little bit of this moving away from 1.4 things dealing with the newer features. Hover and mouse scroll are newer parts and the midi is a bit different so this is likely the spot where adjustments are going to be required.

**Comment by maxbreges** [comment]
Sasha could code a module using a workaround for a non-eliminated-yet bug. I don't think he will have problems re-coding it.
