### ISSUE TITLE
Module's GUI increases its size on every cable connection or "rescan modules"

### ISSUE THREAD

**Issue by maxbreges** [JeffMcClintock/SynthEdit-Bug-Tracking#4]
I'm experiencing strange behaviour with self-increasing size of this particular module in Panel View.
![PatchMemKnobx2](https://github.com/user-attachments/assets/3027ae82-f484-4f0e-aaa7-5434d06c1f4a)
SEM, Cpp and XML are in the attached zip archive.
[PatchMemKnob.zip](https://github.com/user-attachments/files/16648134/PatchMemKnob.zip)

**Comment by JeffMcClintock** [comment]
Please specify your GUI in the XML as below:

`<GUI graphicsApi="GmpiGui">`

I've added a new warning dialog to SynthEdit.

<img width="299" alt="image" src="https://github.com/user-attachments/assets/82979955-4f99-4fde-b3d7-859c93e9c1ea">

**Comment by JeffMcClintock** [comment]
fixed in release 1.5.560

**Comment by maxbreges** [comment]
Thank you

**Comment by maxbreges** [comment]
> @maxbreges Please specify your GUI in the XML as below:
> 
> `<GUI graphicsApi="GmpiGui">`
> 
> I've added a new warning dialog to SynthEdit.
> 
> <img alt="image" width="299" src="https://private-user-images.githubusercontent.com/13861474/359739757-82979955-4f99-4fde-b3d7-859c93e9c1ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzg3MTYsIm5iZiI6MTcyNDIzODQxNiwicGF0aCI6Ii8xMzg2MTQ3NC8zNTk3Mzk3NTctODI5Nzk5NTUtNGY5OS00ZmRlLWIzZDctODU5YzkzZTljMWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDExMDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0OWUwMWJmMDdlNzE1YmZkYjYyYjcyY2M3NGMwZmQxZjkwZmQzODE4NzUzZWNlMGQ2OTg5NmU1MWRjOWI2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wd95SKp9iZfHgPQgAtEMz7QCs9DzelCRF40arB94qGc">

Thank you
