### ISSUE TITLE
Suddenly New, very old and older projects cannot Run, they crash SE, and the DAW

### ISSUE THREAD

**Issue by CodeXSK** [JeffMcClintock/SynthEdit-Bug-Tracking#7]
I don't  know what happened but suddenly I cannot test Run some projects that where used to run fine.
In the DAW I cannotload even older plugins that where working fine! They have error and crash the DAW.

On SE 1.5 they crash SE once I run!  I tried the July version too, the same
If I open them with SE 1.4 is fine!!

The plugins exported from 1.5 when loaded in the DAW they crash or have error!

I am on Win 10

I hope you can find the problem

The last 3 updates I suspect they caused it in Win 10 are these
![image](https://github.com/user-attachments/assets/b21f80d7-871e-4768-86d3-337eed9a81c4)

**Comment by CodeXSK** [comment]
[DC Offset tests.zip](https://github.com/user-attachments/files/16747958/DC.Offset.tests.zip)
For example if you play now this project, it crashes SE!
While its simple and it used to work.

**Comment by JeffMcClintock** [comment]
fixed. I have updated the C++ redistributable that ships with SynthEdit
