### ISSUE TITLE
Blank input fields in the properties panel are replaced by zeros

### ISSUE THREAD

**Issue by Sasha-Radojevic** [JeffMcClintock/SynthEdit-Bug-Tracking#8]
Hi Jeff,

Blank input fields in the properties panel are replaced by zeros.

Here's the state before closing a saved project:
![image](https://github.com/user-attachments/assets/2aa5674c-3e77-4eca-b081-5315ae8ae6e0)

After re-opening the same project:
![image](https://github.com/user-attachments/assets/1dac5b31-162f-4bf0-94b8-1978ef0ee64d)

All my SVG prefabs, and SE projects made with those are affected by this new behavior in a bad way. Elements are not shown because zero means transparent, while blank means default value.

Before (SE 1.4):
![image](https://github.com/user-attachments/assets/9f6f2c13-5eb6-4d0e-a542-23b690c75fa0)

After (SE 1.5):
![image](https://github.com/user-attachments/assets/b97799ba-6ab3-44da-8602-730472b3ea4c)

Here's a test project:
[Blank vs Zero.zip](https://github.com/user-attachments/files/16738047/Blank.vs.Zero.zip)

Steps to reproduce:
1. Open the attached file
2. Click on the container
3. Delete zeros, so input fields are blank
4. Save the project
5. Close the project
6. Reopen the project

You will see that all the fields are filled with zeros.

Thanks,
Sasha

**Comment by JeffMcClintock** [comment]
This issue will be fixed in SynthEdit 1.5 build 561

**Comment by Sasha-Radojevic** [comment]
Awesome, works fine, thank you!
